apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-apps
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd-proj
  source:
    path: .
    repoURL: ssh://git@gitlab.gitlab.jkwong.info/sre/argocd-applications.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
