apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.8.5

resources:
- namespace.yaml
- rolebinding.yaml
- jkwng-git-ssh-secret.yaml
- gitlab-ssh-secret.yaml
- argocd-appproject.yaml
- appproject.yaml
- sre-applications.yaml
- applications.yaml

patchesStrategicMerge:
- argocd-knownhosts-cm.yaml
- argocd-cm.yaml
- argocd-metrics-prometheus.yaml
- argocd-server-prometheus.yaml
- argocd-resources-requests.yaml

namespace: argocd