apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-inception
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd-proj
  source:
    path: overlays/dev-west1
    repoURL: ssh://git@gitlab.gitlab.jkwong.info/sre/argocd-install.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}